version: "3"
services:
  mongo:
    image: bitnami/mongodb:latest
    restart: always
    ports:
      - 27017:27017
    networks:
      - app-network
    volumes:
      - mongodb:/bitnami/mongodb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  mongodb:
    driver: local
